.TH oggconvert 1 2007\-07\-03
.SH NAME
OggConvert \- Converts media files to free formats
.SH SYNOPSIS
.B oggconvert
.SH DESCRIPTION
.B OggConvert
is a small Gnome utility which uses GStreamer to convert 
(almost) any media file to the patent\-free Ogg Vorbis, Theora and 
Dirac formats.
.PP
This version of OggConvert is GUI-only and does not have a command-line 
interface.
.SH OPTIONS
.TP
.B \-\-help-gst
Prints a list of all available GStreamer debugging switches
.SH AVAILABILITY
OggConvert is licensed under the GNU Lesser General Public License (LGPL).
A copy of that license should have come with the package in the file COPYING.
You are encouraged to distribute copies of OggConvert, but please obey the
terms of this license.
.PP
The latest version of OggConvert can be obtained via the project\(cqs
webpage: http://oggconvert.tristanb.net/.
.SH AUTHOR
Tristan Brindle (t.c.brindle@gmail.com)
.PP
This man page originally written by Luca Falavigna
